Document: xfce4-squeezebox-plugin
Title: Debian xfce4-squeezebox-plugin Manual
Author: <insert document author here>
Abstract: This manual describes what xfce4-squeezebox-plugin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xfce4-squeezebox-plugin/xfce4-squeezebox-plugin.sgml.gz

Format: postscript
Files: /usr/share/doc/xfce4-squeezebox-plugin/xfce4-squeezebox-plugin.ps.gz

Format: text
Files: /usr/share/doc/xfce4-squeezebox-plugin/xfce4-squeezebox-plugin.text.gz

Format: HTML
Index: /usr/share/doc/xfce4-squeezebox-plugin/html/index.html
Files: /usr/share/doc/xfce4-squeezebox-plugin/html/*.html

  
